### ISSUE TITLE
looks great, but how in the world do I use it?!? You've gotta add a tutorial cause otherwise people like me are just gonna delete it right after install.

### ISSUE THREAD

**Issue by jshepin** [rbrahul/Smart-Webpage-Ruler#3]

**Comment by rbrahul** [comment]
Here is the youtube tutorial: https://www.youtube.com/embed/FAQV5E1PKAA 
Thanks for pointing

**Comment by jshepin** [comment]
thanks for letting me know, but others won't go to such lengths. it's a beautiful website but it's useless to new users, I recommend in big bold letters "tutorial" or "getting started" at the top of the page or a nav item, otherwise it just makes it more frustrating. Thanks

**Comment by rbrahul** [comment]
Thanks @jshepin I will update the website soon.
